version: '3'
services:
  indoor_nginx:
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - indoorweb
  indoordb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=indoor
      - MYSQL_DATABASE=indoor
      - MYSQL_USER=indoor
      - MYSQL_PASSWORD=indoor
  indoorweb:
    image: hftstuttgart/projectindoorweb
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=indoordb
      - DATABASE_PORT=3306
      - DATABASE_NAME=indoor
      - DATABASE_USER=indoor
      - DATABASE_PASSWORD=indoor
      - CONTEXT_PATH=indoorweb
    volumes:
      - indoor_maps:/root/.projectindoor/floor_maps
    depends_on:
      - indoordb
volumes:
  indoor_maps: