spring:
    http:
        multipart:
            max-file-size: 400MB
            max-request-size: 400MB
    datasource:
        url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

---
spring:
    profiles: prod
    http:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
server:
    context-path: /${CONTEXT_PATH}


